game:
  base_dir: &game_base_dir ~/.factorio
  mods_dir: !join [ *game_base_dir, "/mods" ]

# auth is used for downloading anything from factorio mod portal. Your data is stored only on your pc. Trust me
auth:
  # username is common for authentication with token or password. Your email or like it named - username
  username: null

  # authentication using your token. You can check it in `game base directory`/player-data.json[service-token].
  # if username or token is empty then manager will try to parse it from player-data.json.
  token: null

  password: null

loglevel: WARNING

user:
  base_dir: &user_base_dir ~/.local/share/f_manager
  profiles: !join [ *user_base_dir, "/profiles" ]